### ISSUE TITLE
Don't format content for pre and code elements

### ISSUE THREAD

**Issue by johno** [johnotander/prettify-html#1]
`<pre>` and `<code>` elements should not be reformatted by this plugin. Even the whitespace inside such elements should be considered "meaningful", so:
 - The opening tag should be indented, according to normal logic
 - Contents should remain 100% unaltered (including any whitespace right after the opening tag)
 - The closing tag should not be indented

**Comment by TroyAlford** [comment]
https://github.com/johnotander/prettify-html/pull/5 should address all of the above.
